import {
  BrickWall,
  Calendar,
  Flame,
  Flower,
  HandHeart,
  Heart,
  HelpingHand,
  Lightbulb,
  Sprout,
  Sun,
  Crown,
  Shield,
  Gem,
  Sparkles,
  Stars,
  Moon,
  Wind,
  Medal,
  Zap,
  Compass,
  Sparkle,
  GraduationCap,
  CloudLightning,
  Mountain,
  Trophy,
} from "lucide-react";

// --- CONSTANTS ---
const BADGES = [
  {
    id: "sower",
    name: "The Sower",
    desc: "First Gratitude Entry",
    icon: Sprout,
    condition: (stats) => stats.counts.gratitudes >= 1,
  },
  {
    id: "seeker",
    name: "The Seeker",
    desc: "First Prayer Logged",
    icon: HelpingHand,
    condition: (stats) => stats.counts.prayers >= 1,
  },
  {
    id: "pathfinder",
    name: "Pathfinder",
    desc: "Earn 100 Total XP",
    icon: Compass,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 100,
  },
  {
    id: "morning_star",
    name: "Morning Star",
    desc: "10 Gratitude Entries",
    icon: Sun,
    condition: (stats) => stats.counts.gratitudes >= 10,
  },
  {
    id: "thanksgiving",
    name: "Heart of Thanks",
    desc: "50 Gratitude Entries",
    icon: Heart,
    condition: (stats) => stats.counts.gratitudes >= 50,
  },
  {
    id: "legacy_thanks",
    name: "Legacy of Thanks",
    desc: "100 Gratitude Entries",
    icon: Crown,
    condition: (stats) => stats.counts.gratitudes >= 100,
  },
  {
    id: "warrior",
    name: "Prayer Warrior",
    desc: "10 Prayers Logged",
    icon: Flame,
    condition: (stats) => stats.counts.prayers >= 10,
  },
  {
    id: "pillar_prayer",
    name: "Pillar of Prayer",
    desc: "50 Prayers Logged",
    icon: Gem,
    condition: (stats) => stats.counts.prayers >= 50,
  },
  {
    id: "witness",
    name: "Witness",
    desc: "1 Answered Prayer",
    icon: HandHeart,
    condition: (stats) => stats.answeredPrayersCount >= 1,
  },
  {
    id: "builder",
    name: "Testimony Builder",
    desc: "5 Answered Prayers",
    icon: BrickWall,
    condition: (stats) => stats.answeredPrayersCount >= 5,
  },
  {
    id: "testimony_keeper",
    name: "Testimony Keeper",
    desc: "10 Answered Prayers",
    icon: Sparkles,
    condition: (stats) => stats.answeredPrayersCount >= 10,
  },
  {
    id: "harvest",
    name: "Faithful",
    desc: "3 Day Streak",
    icon: Flower,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 3,
  },
  {
    id: "week",
    name: "Week of Grace",
    desc: "7 Day Streak",
    icon: Lightbulb,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 7,
  },
  {
    id: "fortnight_faith",
    name: "Fortnight of Faith",
    desc: "14 Day Streak",
    icon: Moon,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 14,
  },
  {
    id: "devotion",
    name: "Month of Devotion",
    desc: "30 Day Streak",
    icon: Calendar,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 30,
  },
  {
    id: "season_spirit",
    name: "Season of Spirit",
    desc: "60 Day Streak",
    icon: Wind,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 60,
  },
  {
    id: "centurion_soul",
    name: "Centurion of Soul",
    desc: "100 Day Streak",
    icon: Medal,
    condition: (stats) => (stats.userProfile?.streak || 0) >= 100,
  },
  {
    id: "spirit_2",
    name: "Kindled Spirit",
    desc: "Reach Spirit Level 2",
    icon: Sparkle,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 500,
  },
  {
    id: "acolyte",
    name: "Acolyte of Light",
    desc: "Earn 1,000 Total XP",
    icon: GraduationCap,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 1000,
  },
  {
    id: "spirit_5",
    name: "Steady Flame",
    desc: "Reach Spirit Level 5",
    icon: CloudLightning,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 2000,
  },
  {
    id: "spirit_10",
    name: "Radiant Soul",
    desc: "Reach Spirit Level 10",
    icon: Mountain,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 4500,
  },
  {
    id: "soul_striker",
    name: "Soul Striker",
    desc: "Reach 500 XP",
    icon: Zap,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 500,
  },
  {
    id: "soul_master",
    name: "Soul Master",
    desc: "Earn 5,000 Total XP",
    icon: Trophy,
    condition: (stats) => (stats.userProfile?.experiencePoints || 0) >= 5000,
  },
];

export default BADGES;
